/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab4_gui.bsuir.pokos.frames;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lab4_gui.bsuir.pokos.dao.entity.Sneakers;
import lab4_gui.bsuir.pokos.dao.utils.SneakersDAO;
import lab4_gui.bsuir.pokos.utils.Checks;

/**
 *
 * @author Vladislav
 */
public class MainFrame extends javax.swing.JFrame {

    DefaultTableModel dm;  
    
    public MainFrame() {
        initComponents();
        dm=(DefaultTableModel) sneakersTable.getModel();
        show_sneakers_in_table();
        //sort_table();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        colorsField = new javax.swing.JTextField();
        manufactureField = new javax.swing.JTextField();
        countryField = new javax.swing.JTextField();
        modelField = new javax.swing.JTextField();
        sizeField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        toClearFieldsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sneakersTable = new javax.swing.JTable();

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vladislav\\Desktop\\универ\\Универ\\3курс\\Ситаирис\\LAB4_GUI\\resource\\images\\background.jpg")); // NOI18N
        background.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("League Gothic", 0, 26)); // NOI18N
        jLabel2.setText("Расцветка:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 60));

        jLabel3.setFont(new java.awt.Font("League Gothic", 0, 26)); // NOI18N
        jLabel3.setText("Производитель:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, 60));

        jLabel4.setFont(new java.awt.Font("League Gothic", 0, 26)); // NOI18N
        jLabel4.setText("Страна производства:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, 60));

        jLabel5.setFont(new java.awt.Font("League Gothic", 0, 26)); // NOI18N
        jLabel5.setText("Модель:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 60));

        jLabel6.setFont(new java.awt.Font("League Gothic", 0, 26)); // NOI18N
        jLabel6.setText("Размер:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, 60));

        colorsField.setFont(new java.awt.Font("League Gothic", 0, 24)); // NOI18N
        jPanel1.add(colorsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 250, 40));

        manufactureField.setFont(new java.awt.Font("League Gothic", 0, 24)); // NOI18N
        jPanel1.add(manufactureField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 250, 40));

        countryField.setFont(new java.awt.Font("League Gothic", 0, 24)); // NOI18N
        jPanel1.add(countryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 250, 40));

        modelField.setFont(new java.awt.Font("League Gothic", 0, 24)); // NOI18N
        jPanel1.add(modelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 250, 40));

        sizeField.setFont(new java.awt.Font("League Gothic", 0, 24)); // NOI18N
        jPanel1.add(sizeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 250, 40));

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteButton.setText("Удалить");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 140, 40));

        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.setText("Добавить");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 140, 40));

        toClearFieldsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        toClearFieldsButton.setText("Очистить поля");
        toClearFieldsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toClearFieldsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(toClearFieldsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        sneakersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Модель", "Расцветка", "Размер", "Производитель", "Страна"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sneakersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sneakersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sneakersTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 910, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
         if (manufactureField.getText().length() == 0 ||
                    countryField.getText().length() == 0 ||
                    modelField.getText().length() == 0||
                    colorsField.getText().length() == 0||
                    Checks.isNumber(sizeField.getText())==false) {
                JOptionPane.showMessageDialog(null, "Пожалуйста,проверье корректность введённых данных","Внимание",JOptionPane.WARNING_MESSAGE);
            } else {
             
                Sneakers newSneakers=new Sneakers();
                newSneakers.setColors(colorsField.getText());
                newSneakers.setCountry(countryField.getText());
                newSneakers.setManufacture(manufactureField.getText());
                newSneakers.setModel(modelField.getText());
                newSneakers.setSize(Integer.parseInt(sizeField.getText()));
                
                SneakersDAO dao=new SneakersDAO();
                if(dao.add(newSneakers)) {
                    JOptionPane.showMessageDialog(null, "Информация добавлена!!!", "Добавление", JOptionPane.INFORMATION_MESSAGE);
                    update_table();
                }
                else
                    JOptionPane.showMessageDialog(null, "ERROR 412", "Ошибка!", JOptionPane.ERROR_MESSAGE);
                
                update_table();

            }
         
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if(modelField.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Товар не выбран", "Ошибка!", JOptionPane.WARNING_MESSAGE);
        }
        else{
            
            SneakersDAO dao=new SneakersDAO();
            int id=dao.getID(new Sneakers(0,manufactureField.getText(),countryField.getText(),modelField.getText(),Integer.parseInt(sizeField.getText()),colorsField.getText()));
            if (id!=-1) {
                dao.delete(id);
                JOptionPane.showMessageDialog(null, "Информация о сотруднике удалена", "Удаление", JOptionPane.INFORMATION_MESSAGE);
                update_table();
            }
            else
                JOptionPane.showMessageDialog(null, "Ошибка!", "Ошибка!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void sneakersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sneakersTableMouseClicked
        // display choose row
        int i=sneakersTable.getSelectedRow();
        TableModel model=sneakersTable.getModel();
        
        manufactureField.setText(model.getValueAt(i, 3).toString());
        countryField.setText(model.getValueAt(i, 4).toString());
        modelField.setText(model.getValueAt(i, 0).toString());
        sizeField.setText(model.getValueAt(i, 2).toString());
        colorsField.setText(model.getValueAt(i, 1).toString());
        
        //initialLogin=loginField.getText();
    }//GEN-LAST:event_sneakersTableMouseClicked

    private void toClearFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toClearFieldsButtonActionPerformed
        // TODO add your handling code here:
        manufactureField.setText("");
        countryField.setText("");
        modelField.setText("");
        sizeField.setText("");
        colorsField.setText("");
    }//GEN-LAST:event_toClearFieldsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel background;
    private javax.swing.JTextField colorsField;
    private javax.swing.JTextField countryField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField manufactureField;
    private javax.swing.JTextField modelField;
    private javax.swing.JTextField sizeField;
    private javax.swing.JTable sneakersTable;
    private javax.swing.JButton toClearFieldsButton;
    // End of variables declaration//GEN-END:variables

    private void show_sneakers_in_table() 
    {
        
        ArrayList<Sneakers> result=null;
        SneakersDAO dao=new SneakersDAO();
        
        result= dao.getALL();
        DefaultTableModel model=(DefaultTableModel) sneakersTable.getModel();
        String[] row;            
            
        for(int i=0;i<result.size();i++)
        {     
            row = new String[5]; 
                
            row[0]=result.get(i).getModel();
            row[1]=result.get(i).getColors();
            row[2]=String.valueOf(result.get(i).getSize());
            row[3]=result.get(i).getManufacture();
            row[4]=result.get(i).getCountry();
            model.addRow(row);
        }
        
    }
    
    private void update_table()
    {
        DefaultTableModel model=(DefaultTableModel) sneakersTable.getModel();
        model.setRowCount(0);
        show_sneakers_in_table();
    }
        
}
